### ISSUE TITLE
Storage Request Table Kicks Me Out

### ISSUE THREAD

**Issue by okyloky9** [Lothrazar/Storage-Network#141] opened 2019-04-09 16:00 UTC
Minecraft version & Mod Version: 

MC v1.12.2 , Mod v1.6

Single player or Server:

Single player

Describe problem (what you were doing / what happened):

I try to use (right click) a storage request table, and the GUI will show for ~half a second, and then close itself. I don't crash, it just won't stay up on my screen.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment] 2019-04-19 17:23
How far away is your Master from your GUI block or item?  Is the tile master in a loaded chunk.

I will test this out in a bunch of ways, but it "SHOULD" only disconnect if the Master block breaks or goes into unloaded chunk.

**Comment by LezChap** [comment] 2019-04-21 06:48
Having a similar issue in mod version 1.7.3 in SF 4.0.2...I'll open the table, sometimes it closes immediately, sometimes it lets me start to search for something or pull something out before closing.  Sometimes I tab out of the game and I watch it close while I'm in another window on another screen.  When it happens, there's not a single thing being posted to the console right now, so logs aren't going to be helpful. I also haven't been able to reliably replicate the issue...so far it seems fairly random (it can happen multiple times in quick succession, then I can go awhile without it happening again).

https://imgur.com/4ZFAYtk Screenshot of my system's Master and Request Table...as you can see, both the Master and Request table are in the same chunk, and within a few blocks, so chunk loading shouldn't be the issue.

**Comment by LezChap** [comment] 2019-04-22 07:48
An update:  Had this happen repeatedly to the point that I could not access the GUI of the Request Table for more than a split second.  Closing and re-opening the world didn't fix it, the GUI would auto-close a split second after opening.  This occurred right after re-configuring the network a bit (breaking inventory links and import/export cables, including accidentally breaking and replacing the Master when my pickaxe was too fast and broke 3 blocks in one click. at one point.)  After being kicked from the GUI every attempt, I found a second unused Request Table in a nearby chest, placed it on the network, and THAT one would also auto-close the GUI after it opened momentarily.

After crafting the Ender Chest (the modded version) and getting kicked out of the GUI, being unable to open it again for more than split second, and restarting the world...I went back to the Master, broke it, waited a good few seconds, and then replaced it.  This seemed to resolve my GUI auto-closing issue in this moment.  There isn't a single line in the console/log during this time frame.  I don't know if this will help you track down the issue, but the fact that breaking and replacing the Master (which I assume destroys and re-creates the table or array of network and table devices on the "network" in the code, I haven't looked, the behavior may be pointing to something is "corrupting" that array or table?  If you need me to install and run a debug version of the mod to get more debug data piped to the console the next time this happens, I'd be willing...still haven't found a reliable way to replicate the glitch.

**Comment by johnnyserbe** [comment] 2019-04-22 11:33
I'm having the same issue on SkyFactory 4.0.2 with SimpleStorage 1.7.3. It happened after I added an EnderStorage ender chest with an storage import cable to the network. Restarting the world didn't help but it was fixed after I destroyed and replaced the Network Master.

**Comment by LezChap** [comment] 2019-04-23 12:00
I think I've figured out a way to replicate the issue in my survival world...but couldn't replicate it in a test world.  I'd create the lava file folder crash bug I reported on the Real Filing Cabinet's Github.  (I couldn't get that crash bug to replicate on the test world, even though it has for me in the past, and has for other people in their test worlds.  After trying different ideas for a few minutes, I gave up trying to force the crash in the test world, as obviously there's another interaction/connection I'm missing there.).

However, I can still get the crash to happen reliably on my main world, and when it does, after restarting MC and loading up my world, the Table kicking me from the GUI bug has happened 4 or 5 times in a row, so I think I can reliably replicate it on my end.  This crash wasn't what was causing the GUI-kick issue all the times it's happened to me in the past, but it's a reliable way for me to trigger it into happening.  If I can do anything to try to get more information to track the source/cause of the issue, please let me know.

**Comment by darkhax** [comment] 2019-04-23 19:40
I am having a similar issue, where I am kicked from the GUI. It's just attached to some vanilla chests. Running SF4 4.0.1. No crash or error message but I am on a server. It seems to happen when another player tries to access it but not 100% of the time.

**Comment by okyloky9** [comment] 2019-04-24 14:07
Temporary solution is to break and replace the master controller I found out. What my problem was, was the iron chests used in SF4. (Not the iron chests mod, although I haven't tried it with those yet.) So I'm guessing a lot of non-vanilla storage blocks have issues. Not sure why the all vanilla setup is messing up, good luck dark.

**Comment by darkhax** [comment] 2019-04-24 18:48
I actually narrowed down the issue some more to some reliable reproduction steps. Connect some vanilla chests, have one player in the request table and another player open up a chest that's connected. The player at the request table should be kicked out.

**Comment by cech12** [comment] 2019-04-26 06:12
Maybe it has something to do with this bug report: https://github.com/Darkosto/SkyFactory4Issues/issues/631

**Comment by AstroxV** [comment] 2019-05-16 18:21
I have the same problem, and it is caused by a Storage Import Cable. When an item or multiple items in a quick succession are added through it, it kicks me out of the request table. Breaking the import cable, or disabling items coming through it by blacklisting the, fixes the issue. Replacing the cable and setting the blacklist seems to fix it sometimes.

**Comment by Lothrazar** [comment] 2019-05-29 03:46
https://minecraft.curseforge.com/projects/simple-storage-network/files/2716372

**Closed by Lothrazar** 2019-05-29 03:46 UTC
Labels: bug, done

**Comment by alucard87pl** [comment] 2019-07-18 02:59
I'm having the same issue, in SkyFactory4 (SSN version 1.7.6).
All the chunks that the entire network is in are loaded(I crafted weirding gadhets the moment this issue started), I only have Link and Export cables connecting to vanilla chests, ComPatched Storage chests and drawers from Barrels, Drums, Storage & More.

When I was playing SF4 a while ago, this was not happening and this world is completely new (I've lost the old one and hadn't played for about two months, can't recall which SF4 version was that)

**Comment by deregtd** [comment] 2020-01-02 01:09
Yeah, this is happening for me still with SSN 1.7.8 (in SF4).  What instantly caused it for me was adding a cyclic redstone clock on top of a dispenser, with import/export cables attached to the dispenser.  Every time the redstone clock cycles, the request table closes.

**Comment by Xogue** [comment] 2020-03-16 03:09
Still happening I guess. In my case, it happens when adding an import cable to the network. I have it attached to an ender chest (modded version). (intermediate coding experience here, so take it with a grain of salt) It seems as if whatever timing you have for the import cable to import items is when it closes. like the import cable kicks people out of the grid because it needs to use it.

**Comment by pyriell** [comment] 2021-07-11 15:07
In Minecraft 1.12.2, running version 1.8.1 of this mod, I had this problem when I placed down an AE2Stuff Advanced Inscriber next to the Request Table.  It would open for a second or two and then boot me out.  Removing the inscriber cleared up the issue.
