### ISSUE TITLE
[Bug] Items spreading over multiple storage links while storage not at full capacity

### ISSUE THREAD

**Issue by stijndp** [Lothrazar/Storage-Network#178] opened 2019-05-15 16:14 UTC
Minecraft version & Mod Version: MC Java 1.12.2 + SF4 4.0.5 (storagenetwork 1.7.4)

Single player or Server: SP

Describe problem (what you were doing / what happened):
My early system were 12  288slot compact chests connected via storage link cables.
To expand my capacity I made 540 crates (Barrels, Drums, Storage & More), put 540 storage link cables on them, changed the links on my compact chests to storage import links and connected the new 540 crates to the system.

Expected behaviour: everything goes in their own crates. If a crate overflows, I get multiple crates with a duplicate item but only if the original one overflows.
Behaviour: the same items started going over multiple chests. Wooden crates have 4k capacity and for example I had about 2500 jungle wood that went over 3 different chests.
I expect the behaviour happened when in multiple compact chests the import links were at jungle wood and instead of placing it to the same storage links, they throw it over multiples. (Not sure if this is what happened but it's the only explanation that I can figure out.)

I had about 230 unique items. And while I had room for 540 unique items, all the crates were filled up and there were still items left over in the old compact chests. Many items got duplicated over multiple crates with the same items while they were far from maximum capacity.

Fix suggestion: make an extra check on storage link cables to see if there is storage with the same items and if at least two of those are not at maximum capacity. If at least two are found, move items from the storage with the lowest amount in it to the storage with the highest amount that is not at maximum yet.
I would not suggest making new logic on the import cables designing a system that checks transactions already happening in the system. Adding an extra check on the link cables would, in the eye of the user, already automatically fix if it happens.

**Comment by Lothrazar** [comment] 2019-05-31 14:38
Sounds like this issue only happens when multiple cables are connected to the same inventory. is that correct?

**Comment by stijndp** [comment] 2019-06-05 22:27
They were 18 5x6 walls of crates. At the back hooked up with a 6x5 grid of storage links so one for each crate. Each section of 6x5 storage link cables were connected with 1 normal cable between them since there is a 1 block gap between each section and it all went back to the controller with a single cable.

Sadly I don't have a backup anymore with the setup but I do have a screenshot that can visualise it somewhat.
In the screenshot I locked the crates which did help to keep items from going to empty crates while there were already crates with that item and still with room left. Ofc it does require a lot of manual work for each new resource to manually isolate a section, unlock, fill in the new item, lock again and then reconnect the section.

![MC3](https://user-images.githubusercontent.com/29801608/58993880-19b90480-87ef-11e9-9820-d3f58c1de3f3.png)

**Comment by Forstrei** [comment] 2019-10-20 15:16
I'm getting a similar problem with a small storage network using the Iron Chests mod. I'm not sure which one is causing it. I've got a network with only 8 diamond chests, and every single chest has emeralds in it (among other inefficiently stored items). Every once in a while I'll go manually sort them, but after using the system normally for a day or two the chests get horribly disorganized again and the emeralds will be in multiple chests again. There's other items doing it too, but the emeralds are how I track it. I've got the chests under my house in a 2x4 with a grid of cables on top of them in a 2x4 with the storage network master on top and the request table on top of the master

**Comment by mnsnownutt** [comment] 2020-06-19 21:13
Playing 1.12.2 RAD modpack and experiencing the same issue.  Just tested it again.  I put in 20 rotten flesh and they all went into an empty inventory slot in a chest.  Put in 5 more and then went into a totally different slot in a different chest.  Put in 5 more and went in another totally different slot in a different chest.  Took all of the rotten flesh out and put it back in and it all went into one slot.  This same thing happens with all types of items.  Hope that helps.
![2020-06-19_16 09 09](https://user-images.githubusercontent.com/31514693/85179930-bf4ae480-b247-11ea-8690-031345135618.png)

**Comment by Lothrazar** [comment] 2020-06-27 17:38
"I put in 20 rotten flesh and they all went into an empty inventory slot in a chest. Put in 5 more and then went into a totally different slot in a different chest. Put in 5 more and went in another totally different slot in a different chest. Took all of the rotten flesh out and put it back in and it all went into one slot. This same thing happens with all types of items. Hope that helps."

Yep this is working as intended.  If you want it to use a certain chest every time, you can increase the priority.  Or you can set item filters 

<3

**Closed by Lothrazar** 2020-06-27 17:38 UTC
Labels: 1.12, bug, cannot replicate
